---
name: Yambs Project

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GITHUB_API_TOKEN: ${{secrets.API_TOKEN}}
  CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: [3.14]

    env:
      PYTHON_VERSION: ${{matrix.python-version}}

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: python${{matrix.python-version}} setup
        uses: actions/setup-python@main
        with:
          python-version: ${{matrix.python-version}}
          cache: pip

      - run: pip${{matrix.python-version}} install vmklib>=2.0.12 yambs>=3.1.5 ifgen>=4.7.3

      - run: mk --version
      - run: mbs --version
      - run: ig --version

      - run: mk dz-sync

      - run: mk yaml
      - run: mk python-lint
      - run: mk python-sa

      # - name: setup clang 19
      #   run: |
      #     wget https://apt.llvm.org/llvm.sh
      #     chmod +x ./llvm.sh
      #     sudo ./llvm.sh 19
      #     rm llvm.sh

      - run: sudo apt-get install gcc-14 g++-14 lcov doxygen clang-19 clang-format-19
      # List versions.
      - run: gcc-14 --version
      - run: g++-14 --version
      - run: clang-19 --version
      - run: clang++-19 --version

      - run: mk t variant=clang coverage=false
      - run: ninja all format-check
      - run: mk docs
      - run: mk dist
        if: github.ref_name != 'main'

      # Need to clean because codecov is not finding coverage otherwise.
      - run: mk c keep=debug
      - run: mk t variant=debug

      - uses: codecov/codecov-action@v5
        with:
          gcov_include: build/debug
          gcov_ignore: .mypy_cache
          gcov_executable: gcov-14
          fail_ci_if_error: true
          verbose: true
          token: ${{secrets.CODECOV_TOKEN}}
          slug: libre-embedded/hal-rp2xxx

      - run: mk release
        if: |
          env.GITHUB_API_TOKEN != ''
          && github.ref_name == 'main'
